spring:
  application:
    name: BookStore

  h2:
    console:
      enabled: 'true'
      path: /h2

  r2dbc:
    url: r2dbc:h2:mem:///bookStoreDB
    driver: h2
    username: sa
    password: ''


server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
    enabled: 'true'
  swagger-ui:
    path: /swagger-ui.html




